# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write
jobs:
  tests:
    name: Build and upload
    runs-on: windows-2019
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1
      - name: Restore Packages
        run: nuget restore MapMap.sln
      - name: Build solution
        run: |
          msbuild MapMap.sln -t:rebuild -property:Configuration=Release
          cd bin
          dir
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: asset
          path: ${{ github.workspace }}\bin\Release
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: release.zip
          directory: ${{ github.workspace }}
          path: ${{ github.workspace }}\bin\Release
      - name: Upload artifact.zip
        uses: actions/upload-artifact@v3
        with:
          name: release.zip
          path: ${{ github.workspace }}\release.zip
