name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: MapMap.exe
        path: MapMap.exe
