name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make

    - uses: actions-x/commit@v6
      with:
        name: GitHub Actions
        email: vozdyx.dev@gmail.com
        files: MapMap.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: MapMap.exe
        path: MapMap.exe
