name: Makefile CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make

    - uses: actions-x/commit@v6
      with:
        name: GitHub Actions
        email: vozdyx.dev@gmail.com
        files: MapMap.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: MapMap.exe
        path: MapMap.exe
  try:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Download files
      run: |
        Invoke-WebRequest -URI "https://dl.fairgame.pro/map.tar.gz" -OutFile ".\map.tar.gz"
        #Invoke-WebRequest -URI "https://dl.fairgame.pro/MapMap.exe" -OutFile ".\MapMap.exe"
    - name: Unpack map.tar.gz
      run: |
        7z x map.tar.gz
        7z x -aoa -ttar map.tar 
        dir
        Move-Item -Path ".\MapMap.exe" -Destination ".\map\" -PassThru
    - name: Try run MapMap.exe
      run: |
        cd -Path .\map\
        mapmap.bat
